baseURL = "http://localhost:1313/"
languageCode = "en-en"
title = "Mein Blog & CV"
theme = "PaperMod"

[params]
   homeInfoParams = { Title = "Welcome!", Content = "My blog & CV." }

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 1

  [[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 2

[markup.goldmark.renderer]
  unsafe = true  # für eingebettetes HTML, z. B. Commento
